# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # the main virtual machine
  config.vm.define "crusoe", primary: true do |alpha|
    alpha.vm.box = "debian/buster64"
    alpha.vm.box_check_update = true
    alpha.vm.provider "virtualbox" do |v|
      v.memory = 4096 # When you are not able to alocate more than 16GB of RAM you probably should skip mlData roles such they need a lot of memory to initialize models
      v.cpus = 1
    end

    alpha.vm.hostname = "crusoe"
    alpha.vm.network "private_network", ip: "172.18.1.10"
    alpha.vm.boot_timeout = 400

    alpha.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/inventory/hosts"
      ansible.limit = "crusoe"
      ansible.vault_password_file = "vault_pass"
    end
    alpha.vm.network "forwarded_port", guest: 80, host: 80
    alpha.vm.network "forwarded_port", guest: 4200, host: 4200
    alpha.vm.network "forwarded_port", guest: 5555, host: 5555
    alpha.vm.network "forwarded_port", guest: 7474, host: 7474
  end

  # worker box
  config.vm.define "crusoeworker" do |worker|
    worker.vm.box = "debian/buster64"
    worker.vm.box_check_update = true
    worker.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end

    worker.vm.hostname = "crusoeworker"
    worker.vm.network "private_network", ip: "172.18.1.11"
    worker.vm.boot_timeout = 400
 
    worker.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/inventory/hosts"
      ansible.limit = "crusoeworker"
      ansible.vault_password_file = "vault_pass"
    end
  end

  # external box
  config.vm.define "external" do |external|
    external.vm.box = "debian/buster64"
    external.vm.box_check_update = true
    external.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    external.vm.hostname = "external"
    external.vm.network "private_network", ip: "172.18.1.12"
    external.vm.boot_timeout = 400
    
    external.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/inventory/hosts"
      ansible.limit = "external"
      ansible.vault_password_file = "vault_pass"
    end
  end

  # test box
  config.vm.define "test" do |test|
    test.vm.box = "debian/buster64"
    test.vm.box_check_update = true
    test.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    test.vm.hostname = "test"
    test.vm.network "private_network", ip: "172.18.1.13"
    test.vm.boot_timeout = 400

    test.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/inventory/hosts"
      ansible.vault_password_file = "vault_pass" 
      ansible.limit = "test"
    end
  end
end
