- name: Install ruby
  apt:
    name: ruby-full
    state: present
    cache_valid_time: 1800
    update_cache: yes

- name: Gem - install version 4.0.7  of public_suffix
  gem:
    name: public_suffix
    version: 4.0.7
    state: present

- name: Install nmap
  apt:
    name: nmap
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Install common-tools
  apt:
    name: software-properties-common
    state: present

- name: Download WhatWeb
  git:
    repo: "https://github.com/urbanadventurer/WhatWeb.git"
    dest: "/opt/whatweb/"
    force: yes

- name: Configure WhatWeb
  lineinfile:
    path: "/opt/whatweb/plugins/umbraco.rb"
    insertafter: "matches"
    line: '{ :text=>''<script src="https://cdn.muni.cz/DependencyHandler'' },'

# Install latest available version of addressable (dependency for whatweb).
- gem:
    name: addressable
    state: latest
