---
- hosts: crusoe
  become: true
  roles:
    ## prerequisities
    - pythonPackages
    - commonTools
    ## core components
    - crusoeComponents
    - neo4j
    #- warden
    #- mlData ATLEAST 16Gb Memory required
    ## orchestration
    - configuration
    - redis
    - supervisor
