- name: Delete Debian deb-src backports repository URL in sources list - bug with apt update
  lineinfile:
    path: /etc/apt/sources.list
    state: absent
    backrefs: yes
    regexp: "^(.*https://deb.debian.org/debian buster-backports main.*)$"
  become: yes
  register: deb_archive_changed

# Set Python3.7 as default
- name: Run update-alternatives
  command: "update-alternatives {{ item }}"
  with_items:
    - "--install /usr/bin/python python /usr/bin/python3.7 2"
    - "--install /usr/bin/python python /usr/bin/python2 1"

- name: Copy act-component components
  copy:
    src: "../../../../../../act-component"
    dest: /tmp/

- name: Template a wrapper to sites-available
  template:
    src: generic_wrapper.conf
    dest: "/etc/apache2/sites-available/{{wrapper}}.conf"

- name: Copy directory using command module
  command:
    cmd: cp -r /tmp/act-component/{{dst_wrapper}} /var/www/
  become: yes # Optional: use if you need root permissions

- name: change group for /var/www/{dst_wrapper}
  file:
    path: "/var/www/{{dst_wrapper}}"
    group: www-data
    recurse: yes

- name: check if simulated firewall present
  stat:
    path: /var/www/simulated-pao-firewall/firewall_wrapper_project/simulated_pao_firewall
  register: file_details

- name: change permissions of simulated_pao_firewall
  file:
    path: /var/www/simulated-pao-firewall/firewall_wrapper_project/simulated_pao_firewall
    mode: 0666
  when: file_details.stat.exists

- name: modify ports configuration
  lineinfile:
    path: /etc/apache2/ports.conf
    line: "LISTEN {{firewall_portnumber}}"
    state: present

- name: Add proxypass to default apache site
  lineinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    line: "{{ item.line }}"
    insertbefore: "</VirtualHost>"
  with_items:
    - {
        line: "\tProxyPass /{{ firewall_pao_name }} http://127.0.0.1:{{ firewall_portnumber }}/{{ firewall_pao_name }}",
      }
    - {
        line: "\tProxyPassReverse /{{ firewall_pao_name }} http://127.0.0.1:{{ firewall_portnumber }}/{{ firewall_pao_name }}",
      }

- name: Enable new site
  shell: "/usr/sbin/a2ensite {{wrapper}}.conf"

- name: Reload Apache
  service:
    name: apache2
    state: reloaded

- name: install neo4j package
  pip:
    name: neo4j_driver==1.7.1
    executable: pip3

- name: template neo4j script
  template:
    src: neo4j_update.py
    dest: /tmp/neo4j_update.py

- name: run script
  command: python3 /tmp/neo4j_update.py

- name: remove script after usage
  file:
    path: /tmp/neo4j_update.py
    state: absent
